### ISSUE TITLE
Odd displays when making the response panel smaller

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#15]
![response panel](https://dfl.mn/ROY)

The arrows overlap :(

**Comment by 0xdeafcafe** [comment]
Those arrows are going to be redesigned and moved, but there are still issued with resizing atm 👍

**Comment by 0xdeafcafe** [comment]
Arrows have been fixed, as they're now in the title bar. However it's still wonky with long request url's

**Comment by 0xdeafcafe** [comment]
Finally fixed!
