### ISSUE TITLE
URL panel won't let me start from scratch (always adds `//`)

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#20]
[click here to see video demo](https://giphy.com/gifs/asVG3mG0ut8da7x8jD/html5)

I cannot enter a URL into Beak, it always adds `//` and won't let me remove it

**Comment by 0xdeafcafe** [comment]
Yeah, I did a bunch of work on this to improve it but this bug still remains. It's a real pain the the arse so I'm leaving it until I feel mentally ready to tackle it again. Soon™️
