### ISSUE TITLE
Response body is missing?

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#21]
![no response body](https://dfl.mn/V8q)

Works in Paw :/

**Comment by 0xdeafcafe** [comment]
I think it may be due to the lack of the content-length header! If your service returns it this will work correctly. Although great point that I need to add support for times when this happens.

**Comment by 0xdeafcafe** [comment]
@Duffleman Can we debug this tomorrow over ngrok? Keep to test some complications around not using the Content-Length header around streams. Thanks for finding, as usual :wink:

**Comment by Duffleman** [comment]
![Cuvva does it too](https://dfl.mn/e2o)

Did you know... Cuvva has this same issue? Because Golang does not output content-length haha

**Comment by Duffleman** [comment]
It's to do with content stream, or chunking I _think_

**Comment by 0xdeafcafe** [comment]
CRPC should actually create the content length header when it's creating the response payload. But either way, I've fixed this in https://github.com/beak-app/beak/commit/ee891085065ea575246264aff37f5bf4efa0cdbe
