### ISSUE TITLE
Creating new projects fails

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#30]
![Screenshot](https://dfl.mn/Z7M)

**Comment by Duffleman** [comment]
Build: `00bbd0f9d05a610b1176cdcb2df06328c562effd`

**Comment by 0xdeafcafe** [comment]
Currently revamping a large part of this, should have a stable build up and running in the next few days. After that it should be stable going forward

**Comment by 0xdeafcafe** [comment]
Should be all fixed now 👍
