### ISSUE TITLE
Auto follows redirects

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#60]
Type: Feature request
Platform: N/A

It currently automatically follows redirects, but it'd be cool if it didn't unless I prompted it to?

Example:

https://dfl.mn is a 302 redirect to https://duffleman.co.uk. But when I visit it in beak, it says it is a 200 OK; it didn't show it followed a redirect which could make life difficult for people writing URL shorteners for example

**Comment by 0xdeafcafe** [comment]
Is on the backlog for beta release - https://github.com/beak-app/beak/projects/3#card-52218766

**Comment by 0xdeafcafe** [comment]
All done
