### ISSUE TITLE
Zooming in and out of the UI

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#61]
Type: bug
Platform: macOS (11.1, intel)

Beak respects `Cmd` + `-`, so I can zoom out. But it doesn't respect `Cmd` + `+` to zoom in. I've broken it by zooming out too much and I can't work out how to reset the view :P

**Comment by Duffleman** [comment]
Got it with `Cmd` + `0` :D

**Comment by 0xdeafcafe** [comment]
By default zooming out is `Cmd` + `-`, and zooming in is `Cmd` + `Shift` + `+`. This threw me a little too, I'll see if I can override it to be just `Cmd` + `+`.

**Comment by 0xdeafcafe** [comment]
Fixed in Electron 12 https://github.com/electron/electron/issues/15496.
