### ISSUE TITLE
Monaco editor isn't being bundled correctly

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#63]
Type: bug
Platform: macOS (11.1, intel)

![Screenshot](https://dfl.mn/M6B)

Missing resource files, some missing font files?

**Comment by 0xdeafcafe** [comment]
That is really weird. Looks like it's failing to load the Monaco editor in some form.

**Comment by 0xdeafcafe** [comment]
Fixed in https://github.com/beak-app/beak/commit/c7b4199d6d1f658b9c7f3240b76124c6f084daad
