### ISSUE TITLE
Net errors where the port is not responsive cause beak to crash

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#65]
Type: Bug
Platform: macOS (11.1, intel)

When I point beak to a localhost URL (http://localhost:3000/whoami for example), if there is no server listening on that port, then when I send the request, beak crashes.

![Screenshot](https://dfl.mn/JyL)

**Comment by 0xdeafcafe** [comment]
Ohh interesting, thanks.

**Comment by 0xdeafcafe** [comment]
Fixed here https://github.com/beak-app/beak/commit/3b65416dcd9f5ca27d08637401e2fad52a93601e
