### ISSUE TITLE
Missing ports from HTTP request viewer

### ISSUE THREAD

**Issue by Duffleman** [beak-app/beak#66]
Type: Feature request
Platform: N/A

In the request view, we see:

```
POST /whoami HTTP/1.1
Host: localhost
Connection: close
User-Agent: Beak/0.0.1 (Macintosh; OS X/10.15.4)
Authorization: Bearer eyJhbGciOiJF...
```

But host isn't just `localhost`, it's `localhost:3000`. Not sure what the standard is for that, but could it show it?

**Comment by 0xdeafcafe** [comment]
Deffo should!

**Comment by 0xdeafcafe** [comment]
Fixed
